### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lol768** [Naatan/PHP-CLI#1]
I'm looking into adding some functionality to XenForo-CLI (and subsequently making it installable with composer). It'd be great if I knew what I could do with this library in terms of modification etc.

**Comment by Naatan** [comment]
Added a MIT license. Fyi this is not maintained anymore.

**Comment by lol768** [comment]
Thanks a bunch.

Yeah, I figured this and the XenForo-CLI stuff wasn't actively maintained anymore. I really liked the concept though so I thought I'd try and fork it to fix some issues/add some functionality.

**Comment by Naatan** [comment]
Sounds good. Best of luck!
